### PR TITLE
Use spirv_headers from git

### LINKED ISSUE #10: Update spirv_headers to 1.4.1
Please consider using version 1.4.1 of spirv_headers.
They removed `num_derive` which depends on `syn` (slow build).
This would optimize your build time and help other crates depending on this (see https://github.com/amethyst/rendy/issues/203).

### PR DESCRIPTION
**Pull request by malobre**
Fix #10

### CODE REVIEW

**Comment by malobre** [comment]
If you merge please consider publishing a new version to crates.io :)

**Comment by Jasper-Bekkers** [comment]
@gwihlidal Depending on how quick https://github.com/gfx-rs/rspirv/pull/115 lands you may just want to jump to that instead.

**Comment by malobre** [comment]
https://github.com/gfx-rs/rspirv/pull/115 has been merged and version 1.4.1 has been published on crates.io, closing this.

**Comment by malobre** [comment]
1.4.1 was yanked from crates.io
This PR uses version 1.3.5 from git without the `num-derive` dependency.

**Pull request merged**
